### ISSUE TITLE
Addressing feedback: Updating the backlog ACs, make more comprehensive

### ISSUE THREAD

**Issue by StevenJiao** [CMPUT301F21T06/TheHabitController#37]
Feedback from TA:
"Good work, a little more detail would be nice. ACs should be more comprehensive, such as include edge cases, more details that explicitly state exactly what is in every activity, etc."
Needs to work on our project backlog, update them more clearly, especially our acceptance critaria.

**Comment by Mainul47** [comment]
Updated all In progress and to do backlogs with more details for acceptance criteria and edge cases.
